# Generated by Django 3.2.5 on 2024-02-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas', models.CharField(max_length=20)),
                ('chemical_symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(choices=[('Single liner only', 'Single liner only'), ('Double liner only', 'Double liner only'), ('Target only', 'Target only'), ('Single liner on target', 'Single liner on target'), ('Double liner on target', 'Double liner on target')], default='Single liner only', max_length=50)),
                ('outer_press', models.FloatField(blank=True, null=True)),
                ('inner_press', models.FloatField(blank=True, null=True)),
                ('taget_press', models.FloatField(blank=True, null=True)),
                ('outer_timing', models.IntegerField(blank=True, null=True)),
                ('inner_timing', models.IntegerField(blank=True, null=True)),
                ('target_timing', models.IntegerField(blank=True, null=True)),
                ('inner_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_gas', to='shots.gas')),
                ('outer_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outer_gas', to='shots.gas')),
                ('target_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_gas', to='shots.gas')),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='liners',
        ),
        migrations.RemoveField(
            model_name='test',
            name='target',
        ),
        migrations.AlterField(
            model_name='diagnosticimage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='shots.test'),
        ),
        migrations.DeleteModel(
            name='Liner',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.AddField(
            model_name='test',
            name='gasConfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gasConfig', to='shots.gasconfig'),
        ),
    ]
