# Generated by Django 3.2.5 on 2024-02-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0002_auto_20240209_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasconfig',
            name='inner_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_gas', to='shots.gas'),
        ),
        migrations.AlterField(
            model_name='gasconfig',
            name='outer_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outer_gas', to='shots.gas'),
        ),
        migrations.AlterField(
            model_name='gasconfig',
            name='target_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_gas', to='shots.gas'),
        ),
    ]
