# Generated by Django 3.2.5 on 2024-02-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0005_auto_20240209_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('num', models.IntegerField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('outer_press', models.FloatField(blank=True, null=True)),
                ('inner_press', models.FloatField(blank=True, null=True)),
                ('taget_press', models.FloatField(blank=True, null=True)),
                ('outer_timing', models.IntegerField(blank=True, null=True)),
                ('inner_timing', models.IntegerField(blank=True, null=True)),
                ('target_timing', models.IntegerField(blank=True, null=True)),
                ('gasConfig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gasConfig', to='shots.gasconfig')),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosticimage',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='diagnosticimage',
            name='shot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shot', to='shots.shot'),
        ),
    ]
