# Generated by Django 3.2.5 on 2024-02-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0006_auto_20240210_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasconfig',
            name='inner_gas',
        ),
        migrations.RemoveField(
            model_name='gasconfig',
            name='outer_gas',
        ),
        migrations.RemoveField(
            model_name='gasconfig',
            name='target_gas',
        ),
        migrations.AddField(
            model_name='gasconfig',
            name='inner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner', to='shots.gas'),
        ),
        migrations.AddField(
            model_name='gasconfig',
            name='outer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outer', to='shots.gas'),
        ),
        migrations.AddField(
            model_name='gasconfig',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='shots.gas'),
        ),
    ]
