# Generated by Django 3.2.5 on 2024-02-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0007_auto_20240227_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot',
            old_name='taget_press',
            new_name='target_press',
        ),
    ]
