# Generated by Django 3.2.5 on 2024-03-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0008_rename_taget_press_shot_target_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticimage',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
