# Generated by Django 3.2.5 on 2024-03-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0009_alter_diagnosticimage_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='current_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='dip_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticimage',
            name='shot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticImage', to='shots.shot'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='gasConfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shot', to='shots.gasconfig'),
        ),
    ]
