# Generated by Django 3.2.5 on 2024-03-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0010_auto_20240308_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('start', models.FloatField(blank=True, null=True)),
                ('peak_time', models.FloatField(blank=True, null=True)),
                ('peak_volt', models.FloatField(blank=True, null=True)),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xrayDetector', to='shots.shot')),
            ],
        ),
    ]
