# Generated by Django 3.2.5 on 2024-03-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0013_auto_20240308_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='XuvCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('frame1', models.FloatField(blank=True, null=True)),
                ('frame2', models.FloatField(blank=True, null=True)),
                ('frame3', models.FloatField(blank=True, null=True)),
                ('frame4', models.FloatField(blank=True, null=True)),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xuvCamera', to='shots.shot')),
            ],
        ),
    ]
