# Generated by Django 3.2.5 on 2024-03-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0014_xuvcamera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XuvCamera',
            new_name='XuvImage',
        ),
    ]
