# Generated by Django 3.2.5 on 2024-03-09 02:07

from django.db import migrations, models
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0015_rename_xuvcamera_xuvimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuvimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shots.models.image_upload_dir),
        ),
    ]
