# Generated by Django 3.2.5 on 2024-03-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0016_xuvimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuvimage',
            name='shot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xuvImage', to='shots.shot'),
        ),
        migrations.DeleteModel(
            name='DiagnosticImage',
        ),
    ]
