# Generated by Django 3.2.5 on 2024-03-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0017_auto_20240308_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='cavity_p',
            field=models.FloatField(blank=True, default=77, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='cavity_v',
            field=models.FloatField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='maxwell_p',
            field=models.FloatField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='premag_t',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='premag_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='trigger_p',
            field=models.FloatField(blank=True, default=35, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='trigger_v',
            field=models.FloatField(blank=True, default=60, null=True),
        ),
    ]
