# Generated by Django 3.2.5 on 2024-03-16 02:31

from django.db import migrations, models
import django.db.models.deletion
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0018_auto_20240309_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schlieren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shots.models.image_upload_dir)),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schlieren', to='shots.shot')),
            ],
        ),
    ]
