# Generated by Django 3.2.5 on 2024-03-28 18:43

from django.db import migrations, models
import django.db.models.deletion
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0019_schlieren'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='amfB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='amfCharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='bubbles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='postNotes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shot',
            name='preNotes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='xuvimage',
            name='charge',
            field=models.FloatField(blank=True, default=4.4, null=True),
        ),
        migrations.CreateModel(
            name='Spectrometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(blank=True, null=True)),
                ('exposureTime', models.FloatField(blank=True, null=True)),
                ('gain', models.FloatField(blank=True, null=True)),
                ('grating', models.FloatField(blank=True, null=True)),
                ('centralWavelength', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shots.models.image_upload_dir)),
                ('pinhole', models.CharField(blank=True, max_length=50, null=True)),
                ('mica', models.CharField(blank=True, max_length=50, null=True)),
                ('hopg', models.CharField(blank=True, max_length=50, null=True)),
                ('xuv', models.CharField(blank=True, max_length=50, null=True)),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectrometer', to='shots.shot')),
            ],
        ),
        migrations.CreateModel(
            name='Interferometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shots.models.image_upload_dir)),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interferometer', to='shots.shot')),
            ],
        ),
    ]
