# Generated by Django 3.2.5 on 2024-04-02 00:45

from django.db import migrations, models
import django.db.models.deletion
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0020_auto_20240328_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='loadType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interferometer',
            name='image',
            field=models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir),
        ),
        migrations.AlterField(
            model_name='schlieren',
            name='image',
            field=models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir),
        ),
        migrations.AlterField(
            model_name='spectrometer',
            name='image',
            field=models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir),
        ),
        migrations.AlterField(
            model_name='xraydetector',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xrayDetector', to='shots.filter'),
        ),
        migrations.AlterField(
            model_name='xuvimage',
            name='image',
            field=models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir),
        ),
    ]
