# Generated by Django 3.2.5 on 2024-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0021_auto_20240401_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['num']},
        ),
        migrations.RemoveField(
            model_name='shot',
            name='time',
        ),
        migrations.AddField(
            model_name='shot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
