# Generated by Django 3.2.5 on 2024-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0022_auto_20240411_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
