# Generated by Django 3.2.5 on 2024-11-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0023_shot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuvimage',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
