# Generated by Django 3.2.5 on 2024-11-19 00:18

from django.db import migrations, models
import django.db.models.deletion
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0024_alter_xuvimage_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ['-num']},
        ),
        migrations.CreateModel(
            name='ScopePlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras', models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir)),
                ('gas_timing', models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir)),
                ('current', models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir)),
                ('switches', models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir)),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopePlots', to='shots.shot')),
            ],
        ),
    ]
