# Generated by Django 3.2.5 on 2024-12-04 01:18

from django.db import migrations, models
import django.db.models.deletion
import shots.models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0025_auto_20241118_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('fluence', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('n_yield', models.FloatField(blank=True, null=True)),
                ('plots', models.ImageField(blank=True, default='images/noImage.png', null=True, upload_to=shots.models.image_upload_dir)),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activationDetector', to='shots.shot')),
            ],
        ),
    ]
