# Generated by Django 3.2.5 on 2024-12-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0026_activationdetector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='loadType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
