# Generated by Django 3.2.5 on 2024-12-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0027_alter_shot_loadtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='postNotes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='preNotes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
